### ISSUE TITLE
own commits don't show when organization membership is private

### ISSUE THREAD

**Issue by prettycoder** [pulseenergy/panorama#7]
When a user's organization membership is set to private, then the own commits will not show in that user's view. Also the repos will be prefixed with the organization name.

Workaround: Set membership in the organization to public and the commits will show and the prefix disappears. It may be necessary to clear the panorama cookie to see this.

**Comment by rsarvaria** [comment]
Can I be removed from this mailing list?

**Comment by supermitch** [comment]
There's a button on the right of this page (https://github.com/pulseenergy/panorama/issues/7#issuecomment-141233887) that says "unsubscribe", will that do it?

**Comment by canadianveggie** [comment]
@rsarvaria https://github.com/pulseenergy/panorama/watchers
